# Generated by Django 4.1 on 2023-06-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_rent_announcement_sell_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='image',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
