# Generated by Django 4.1 on 2023-06-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_messages_delete_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='enddate',
        ),
    ]
